name: Docker Image CI

on:
  push:
    branches: [main]
    tags: ['v*']
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compute tags
        id: t
        run: |
          SHORT=$(git rev-parse --short HEAD)
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            SEMVER="${GITHUB_REF##*/}"
            echo "web_tags=${{ secrets.DOCKERHUB_USERNAME }}/expensely-web:${SEMVER},${{ secrets.DOCKERHUB_USERNAME }}/expensely-web:latest" >> $GITHUB_OUTPUT
            echo "web_unique=${{ secrets.DOCKERHUB_USERNAME }}/expensely-web:${SEMVER}+${SHORT}" >> $GITHUB_OUTPUT
            echo "api_tags=${{ secrets.DOCKERHUB_USERNAME }}/expensely-api:latest" >> $GITHUB_OUTPUT
            echo "api_unique=${{ secrets.DOCKERHUB_USERNAME }}/expensely-api:${SEMVER}+${SHORT}" >> $GITHUB_OUTPUT
            echo "app_version=${SEMVER}" >> $GITHUB_OUTPUT
          else
            echo "web_tags=${{ secrets.DOCKERHUB_USERNAME }}/expensely-web:edge" >> $GITHUB_OUTPUT
            echo "web_unique=${{ secrets.DOCKERHUB_USERNAME }}/expensely-web:edge-${SHORT}" >> $GITHUB_OUTPUT
            echo "api_tags=${{ secrets.DOCKERHUB_USERNAME }}/expensely-api:edge" >> $GITHUB_OUTPUT
            echo "api_unique=${{ secrets.DOCKERHUB_USERNAME }}/expensely-api:edge-${SHORT}" >> $GITHUB_OUTPUT
            echo "app_version=${SHORT}" >> $GITHUB_OUTPUT
          fi
          echo "short_sha=${SHORT}" >> $GITHUB_OUTPUT

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build+push API
        uses: docker/build-push-action@v5
        with:
          context: ./api
          file: ./api/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ steps.t.outputs.api_tags }}
            ${{ steps.t.outputs.api_unique }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build+push Web
        uses: docker/build-push-action@v5
        with:
          context: ./web
          file: ./web/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ steps.t.outputs.web_tags }}
            ${{ steps.t.outputs.web_unique }}
          build-args: |
            APP_VERSION=${{ steps.t.outputs.app_version }}
            GIT_SHA=${{ steps.t.outputs.short_sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
